[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Marsel"
version = "0.0.1"
description = "A lightweight utility library"
authors = [{ name="Shaxzodbek" }]
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/shaxzodbek16/marsel"

dependencies = [
    "passlib[bcrypt]>=1.7.4",
]